version: '3'
services:
  python_app:
    build: .
    ports:
      - "5000:5000"  # Python
      - "3000:3000"  # Node.js
  db:
    image: mysql:8
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  mysqldata:
